[package]
name = "redis-godot"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]  # Compile this crate to a dynamic C library.

[dependencies]
godot = "0.2.0"
lazy_static = "1.5.0"
r2d2 = "0.8.10"
redis = { version = "0.27.6", features = ["r2d2"] }
