name: Deploy to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          'lfs': true
      - name: CheckoutLFS
        uses: actions/checkout@v4
      - run: git lfs pull

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Determine parallel jobs
        run: echo "JOBS=$(nproc)" >> $GITHUB_ENV

      - name: Build web image (web-build target)
        uses: docker/build-push-action@v6
        with:
          context: .
          target: web-build
          tags: local/spesscomputer:web-build
          load: true
          pull: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            JOBS=${{ env.JOBS }}

      - name: Extract built site from image
        run: |
          cid=$(docker create local/spesscomputer:web-build)
          docker cp "$cid":/src/web/build ./build
          docker rm "$cid"
          test -f ./build/index.html || (echo "index.html not found in build" && ls -la ./build && exit 1)

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./build

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4   